# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: GEODES Research Group
email: genielog@iro.umontreal.ca
#description: >- # this means to ignore newlines until "baseurl:"
#  Département d'informatique et de recherche opérationnelle
#  Université de Montréal
#  C.P. 6128 Succursale Centre-ville
#  Montréal (QC) CANADA H3C 3J7
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: umontrealgeodes
github_username:  geodes-sms
address: |-
  Département d'informatique et de recherche opérationnelle
  Université de Montréal
  C.P. 6128 Succursale Centre-ville
  Montréal (QC) CANADA H3C 3J7
show_excerpts: true

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

site-css:
- "/assets/css/normalize.css"
- "/assets/css/base.css"
- "/assets/css/team.css"
- "/assets/css/style-geodes.css"
- "/assets/css/events.css"
#- "/assets/css/page-people.css"
#- "/assets/css/page-projects.css"

navigation:
- title: Home
  url: /
- title: People
  url: /people
- title: Research
  subpages:
    - title: publications
      url: /publications
    - title: projects
      url: /projects
    - title: tools
      url: /tools
- title: Events
  subpages:
    - title: seminar
      url: /events/seminar
    - title: Research Day
      url: /events/research-day-and-symposium-2022
- title: Teaching
  url: /teaching
- title: Contact
  url: /contact
